# Site
name: 'Carlos C. Dias'
description: 'Tech, politics, experiences'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'carloscdias-com'
email: 'carlosdias.dev@gmail.com'
mailchimp-list: 'https://carloscdias.us4.list-manage.com/subscribe/post?u=679ffc9737e4e61d6b45ca49e&amp;id=41925b50cb'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    carlos:
      name:           Carlos
      site:           https://carloscdias.com
      avatar:         assets/images/avatar.jpg
      bio:            "Hi, I am Carlos, SWE 3x @ Google, 2x @ UNICEF and author of this blog. I like to make things work and hope you enjoy the experiences I am going to share here."
      email:          carlosdias.dev@gmail.com
      twitter:        https://twitter.com/devesquerdinha

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: carlos
      avatar: assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
